-- ============================================
-- 档案审核管理系统 - 数据库表结构
-- 版本: 1.0
-- 说明: 此文件包含系统所需的所有数据库表结构
-- ============================================

-- 1. 用户角色表
CREATE TABLE IF NOT EXISTS `user_role` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `role_name` varchar(50) NOT NULL COMMENT '角色名称',
  `role_code` int(11) NOT NULL DEFAULT '1' COMMENT '角色代码：0=管理员，1=普通用户',
  PRIMARY KEY (`id`),
  UNIQUE KEY `role_code` (`role_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户角色表';

-- 2. 用户表
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `password` varchar(255) NOT NULL COMMENT '密码（bcrypt加密）',
  `role_id` int(11) NOT NULL DEFAULT '1' COMMENT '角色ID',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `role_id` (`role_id`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `user_role` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 3. 系统设置表
CREATE TABLE IF NOT EXISTS `system_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `param_key` varchar(100) NOT NULL COMMENT '参数键',
  `param_value` text COMMENT '参数值',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `param_key` (`param_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统设置表';

-- 4. 操作日志表
CREATE TABLE IF NOT EXISTS `operation_logs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `action` varchar(500) NOT NULL COMMENT '操作内容',
  `ip` varchar(50) DEFAULT NULL COMMENT 'IP地址',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `username` (`username`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';

-- 5. 设备建档明细表（fileList）
CREATE TABLE IF NOT EXISTS `fileList` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_code` varchar(100) NOT NULL COMMENT '设备编码',
  `original_device_code` varchar(100) DEFAULT NULL COMMENT '原设备编码',
  `device_name` varchar(200) NOT NULL COMMENT '设备名称',
  `division_code` varchar(50) NOT NULL COMMENT '行政区划编码',
  `monitor_point_type` varchar(10) NOT NULL COMMENT '监控点位类型：1=一类点，2=二类点，3=三类点，4=四类点',
  `pickup` varchar(50) DEFAULT NULL COMMENT '拾音器',
  `parent_device` varchar(100) DEFAULT NULL COMMENT '父设备',
  `construction_unit` varchar(200) NOT NULL COMMENT '建设单位/设备归属',
  `construction_unit_code` varchar(100) NOT NULL COMMENT '建设单位/平台归属代码',
  `management_unit` varchar(200) NOT NULL COMMENT '管理单位',
  `camera_dept` varchar(100) NOT NULL COMMENT '摄像机所属部门（警种）',
  `admin_name` varchar(50) NOT NULL COMMENT '管理员姓名',
  `admin_contact` varchar(50) NOT NULL COMMENT '管理员联系电话',
  `contractor` varchar(200) NOT NULL COMMENT '承建单位',
  `maintain_unit` varchar(200) NOT NULL COMMENT '维护单位',
  `device_vendor` varchar(100) NOT NULL COMMENT '设备厂商',
  `device_model` varchar(100) DEFAULT NULL COMMENT '设备型号',
  `camera_type` varchar(50) NOT NULL COMMENT '摄像机类型',
  `access_method` varchar(50) DEFAULT NULL COMMENT '接入方式',
  `camera_function_type` varchar(50) NOT NULL COMMENT '摄像机功能类型：1=车辆，2=人脸，空或其他=视频',
  `video_encoding_format` varchar(50) NOT NULL COMMENT '视频编码格式',
  `image_resolution` varchar(50) NOT NULL COMMENT '图像分辨率',
  `camera_light_property` varchar(50) DEFAULT NULL COMMENT '摄像机补光属性',
  `backend_structure` varchar(50) DEFAULT NULL COMMENT '后端结构化',
  `lens_type` varchar(50) DEFAULT NULL COMMENT '镜头类型',
  `installation_type` varchar(50) DEFAULT NULL COMMENT '安装类型',
  `height_type` varchar(50) NOT NULL COMMENT '高度类型',
  `jurisdiction_police` varchar(200) NOT NULL COMMENT '所属辖区公安机关',
  `installation_address` varchar(500) NOT NULL COMMENT '安装地址',
  `surrounding_landmark` varchar(500) NOT NULL COMMENT '周边标志',
  `longitude` decimal(10,7) NOT NULL COMMENT '经度',
  `latitude` decimal(10,7) NOT NULL COMMENT '纬度',
  `installation_location` varchar(50) NOT NULL COMMENT '摄像机安装位置室内外',
  `monitoring_direction` varchar(50) NOT NULL COMMENT '摄像机监控方位',
  `pole_number` varchar(50) NOT NULL COMMENT '立杆编号',
  `scene_picture` varchar(500) DEFAULT NULL COMMENT '摄像机实景图片',
  `networking_property` varchar(50) DEFAULT NULL COMMENT '联网属性',
  `access_network` varchar(50) NOT NULL COMMENT '接入网络',
  `ipv4_address` varchar(50) NOT NULL COMMENT 'IPv4地址',
  `ipv6_address` varchar(50) DEFAULT NULL COMMENT 'IPv6地址',
  `mac_address` varchar(50) NOT NULL COMMENT '设备MAC地址',
  `access_port` varchar(50) DEFAULT NULL COMMENT '访问端口',
  `associated_encoder` varchar(100) DEFAULT NULL COMMENT '关联编码器',
  `device_username` varchar(50) DEFAULT NULL COMMENT '设备用户名',
  `device_password` varchar(100) DEFAULT NULL COMMENT '设备口令',
  `channel_number` varchar(50) DEFAULT NULL COMMENT '通道号',
  `connection_protocol` varchar(50) DEFAULT NULL COMMENT '连接协议',
  `enabled_time` varchar(50) NOT NULL COMMENT '启用时间',
  `scrapped_time` varchar(50) DEFAULT NULL COMMENT '报废时间',
  `device_status` varchar(50) NOT NULL COMMENT '设备状态',
  `inspection_status` varchar(50) DEFAULT NULL COMMENT '巡检状态',
  `video_loss` int(11) DEFAULT NULL COMMENT '视频丢失',
  `color_distortion` int(11) DEFAULT NULL COMMENT '色彩失真',
  `video_blur` int(11) DEFAULT NULL COMMENT '视频模糊',
  `brightness_exception` int(11) DEFAULT NULL COMMENT '亮度异常',
  `video_interference` int(11) DEFAULT NULL COMMENT '视频干扰',
  `video_lag` int(11) DEFAULT NULL COMMENT '视频卡顿',
  `video_occlusion` int(11) DEFAULT NULL COMMENT '视频遮挡',
  `scene_change` int(11) DEFAULT NULL COMMENT '场景变更',
  `online_duration` bigint(20) DEFAULT NULL COMMENT '在线时长',
  `offline_duration` bigint(20) DEFAULT NULL COMMENT '离线时长',
  `signaling_delay` bigint(20) DEFAULT NULL COMMENT '信令时延',
  `video_stream_delay` bigint(20) DEFAULT NULL COMMENT '视频流时延',
  `key_frame_delay` bigint(20) DEFAULT NULL COMMENT '关键帧时延',
  `recording_retention_days` int(11) NOT NULL COMMENT '录像保存天数',
  `storage_device_code` varchar(100) DEFAULT NULL COMMENT '存储设备编码',
  `storage_channel_number` varchar(50) DEFAULT NULL COMMENT '存储通道号',
  `storage_type` varchar(50) DEFAULT NULL COMMENT '存储类型',
  `cache_settings` varchar(200) DEFAULT NULL COMMENT '缓存设置',
  `notes` text DEFAULT NULL COMMENT '备注',
  `collection_area_type` varchar(50) NOT NULL COMMENT '采集区域类型',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `audit_status` int(11) NOT NULL DEFAULT '0' COMMENT '建档状态：0=未审核未建档，1=已审核未建档，2=已建档',
  PRIMARY KEY (`id`),
  KEY `device_code` (`device_code`),
  KEY `device_name` (`device_name`),
  KEY `update_time` (`update_time`),
  KEY `audit_status` (`audit_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备建档明细表';

-- 6. 卡口建档明细表（checkpoint_details）
CREATE TABLE IF NOT EXISTS `checkpoint_details` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `checkpoint_code` varchar(100) DEFAULT NULL COMMENT '卡口编号',
  `original_checkpoint_code` varchar(100) DEFAULT NULL COMMENT '原卡口编号',
  `checkpoint_name` varchar(200) DEFAULT NULL COMMENT '卡口名称',
  `checkpoint_address` varchar(500) DEFAULT NULL COMMENT '卡口地址',
  `road_name` varchar(200) DEFAULT NULL COMMENT '道路名称',
  `direction_type` varchar(50) DEFAULT NULL COMMENT '方向类型',
  `direction_description` varchar(500) DEFAULT NULL COMMENT '方向描述',
  `direction_notes` varchar(500) DEFAULT NULL COMMENT '方向备注',
  `division_code` varchar(50) DEFAULT NULL COMMENT '行政区划',
  `road_section_type` varchar(50) DEFAULT NULL COMMENT '路段类型',
  `road_code` varchar(100) DEFAULT NULL COMMENT '道路代码',
  `kilometer_or_intersection_number` varchar(100) DEFAULT NULL COMMENT '公里数/路口号',
  `road_meter` varchar(100) DEFAULT NULL COMMENT '道路米数',
  `pole_number` varchar(50) DEFAULT NULL COMMENT '立杆编号',
  `checkpoint_point_type` varchar(10) DEFAULT NULL COMMENT '卡口点位类型：1=一类点，2=二类点，3=三类点，4=四类点',
  `checkpoint_location_type` varchar(50) DEFAULT NULL COMMENT '卡口位置类型',
  `checkpoint_application_type` varchar(50) DEFAULT NULL COMMENT '卡口应用类型',
  `has_interception_condition` varchar(10) DEFAULT NULL COMMENT '具备拦截条件',
  `has_speed_measurement` varchar(10) DEFAULT NULL COMMENT '具备车辆测速功能',
  `has_realtime_video` varchar(10) DEFAULT NULL COMMENT '具备实时视频功能',
  `has_face_capture` varchar(10) DEFAULT NULL COMMENT '具备人脸抓拍功能',
  `has_violation_capture` varchar(10) DEFAULT NULL COMMENT '具备违章抓拍功能',
  `has_frontend_secondary_recognition` varchar(10) DEFAULT NULL COMMENT '具备前端二次识别功能',
  `is_boundary_checkpoint` varchar(10) DEFAULT NULL COMMENT '是否边界卡口',
  `adjacent_area` varchar(200) DEFAULT NULL COMMENT '邻界地域',
  `checkpoint_longitude` varchar(50) DEFAULT NULL COMMENT '卡口经度',
  `checkpoint_latitude` varchar(50) DEFAULT NULL COMMENT '卡口纬度',
  `checkpoint_scene_photo_url` varchar(500) DEFAULT NULL COMMENT '卡口实景照片地址',
  `checkpoint_status` varchar(50) DEFAULT NULL COMMENT '卡口状态',
  `capture_trigger_type` varchar(50) DEFAULT NULL COMMENT '抓拍触发类型',
  `capture_direction_type` varchar(50) DEFAULT NULL COMMENT '抓拍方向类型',
  `total_lanes` varchar(10) DEFAULT NULL COMMENT '车道总数',
  `panoramic_camera_device_code` varchar(100) DEFAULT NULL COMMENT '全景球机设备编码',
  `next_checkpoint_along_road` varchar(100) DEFAULT NULL COMMENT '沿线下一卡口编号',
  `next_checkpoint_opposite` varchar(100) DEFAULT NULL COMMENT '对向下一卡口编号',
  `next_checkpoint_left_turn` varchar(100) DEFAULT NULL COMMENT '左转下一卡口编号',
  `next_checkpoint_right_turn` varchar(100) DEFAULT NULL COMMENT '右转下一卡口编号',
  `next_checkpoint_u_turn` varchar(100) DEFAULT NULL COMMENT '掉头下一卡口编号',
  `construction_unit` varchar(200) DEFAULT NULL COMMENT '建设单位',
  `management_unit` varchar(200) DEFAULT NULL COMMENT '管理单位',
  `checkpoint_department` varchar(100) DEFAULT NULL COMMENT '卡口所属部门',
  `admin_name` varchar(50) DEFAULT NULL COMMENT '管理员姓名',
  `admin_contact` varchar(50) DEFAULT NULL COMMENT '管理员联系电话',
  `checkpoint_contractor` varchar(200) DEFAULT NULL COMMENT '卡口承建单位',
  `checkpoint_maintain_unit` varchar(200) DEFAULT NULL COMMENT '卡口维护单位',
  `alarm_receiving_department` varchar(200) DEFAULT NULL COMMENT '接警部门',
  `alarm_receiving_department_code` varchar(100) DEFAULT NULL COMMENT '接警部门代码',
  `alarm_receiving_phone` varchar(50) DEFAULT NULL COMMENT '接警电话',
  `interception_department` varchar(200) DEFAULT NULL COMMENT '拦截部门',
  `interception_department_code` varchar(100) DEFAULT NULL COMMENT '拦截部门代码',
  `interception_department_contact` varchar(50) DEFAULT NULL COMMENT '拦截部门联系电话',
  `terminal_code` varchar(100) DEFAULT NULL COMMENT '终端编码',
  `terminal_ip_address` varchar(50) DEFAULT NULL COMMENT '终端IP地址',
  `terminal_port` varchar(50) DEFAULT NULL COMMENT '终端端口',
  `terminal_username` varchar(50) DEFAULT NULL COMMENT '终端用户名',
  `terminal_password` varchar(100) DEFAULT NULL COMMENT '终端密码',
  `terminal_vendor` varchar(100) DEFAULT NULL COMMENT '终端厂商',
  `checkpoint_enabled_time` varchar(50) DEFAULT NULL COMMENT '卡口启用时间',
  `checkpoint_revoked_time` varchar(50) DEFAULT NULL COMMENT '卡口撤销时间',
  `notes` text DEFAULT NULL COMMENT '备注',
  `checkpoint_device_type` varchar(50) DEFAULT NULL COMMENT '卡口设备类型',
  `total_capture_cameras` varchar(10) DEFAULT NULL COMMENT '抓拍摄像机总数',
  `central_control_code` varchar(100) DEFAULT NULL COMMENT '中控机编码',
  `central_control_ip_address` varchar(50) DEFAULT NULL COMMENT '中控机IP地址',
  `central_control_port` varchar(50) DEFAULT NULL COMMENT '中控机端口',
  `central_control_username` varchar(50) DEFAULT NULL COMMENT '中控机用户名',
  `central_control_password` varchar(100) DEFAULT NULL COMMENT '中控机密码',
  `central_control_vendor` varchar(100) DEFAULT NULL COMMENT '中控机厂商',
  `checkpoint_scrapped_time` varchar(50) DEFAULT NULL COMMENT '卡口报废时间',
  `total_antennas` varchar(10) DEFAULT NULL COMMENT '天线总数',
  `terminal_mac_address` varchar(50) DEFAULT NULL COMMENT '终端MAC地址',
  `collection_area_type` varchar(50) DEFAULT NULL COMMENT '采集区域类型',
  `integrated_command_platform_checkpoint_code` varchar(200) DEFAULT NULL COMMENT '集成指挥平台卡口编号（组）',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `audit_status` int(11) NOT NULL DEFAULT '0' COMMENT '建档状态：0=未审核未建档，1=已审核未建档，2=已建档',
  PRIMARY KEY (`id`),
  KEY `task_id` (`task_id`),
  KEY `checkpoint_code` (`checkpoint_code`),
  KEY `checkpoint_name` (`checkpoint_name`),
  KEY `update_time` (`update_time`),
  KEY `audit_status` (`audit_status`),
  CONSTRAINT `checkpoint_details_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `checkpoint_tasks` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='卡口建档明细表';

-- 7. 设备审核任务表（audit_tasks）
CREATE TABLE IF NOT EXISTS `audit_tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `file_name` varchar(200) NOT NULL COMMENT '档案名称',
  `organization` varchar(200) NOT NULL COMMENT '机构名称',
  `import_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '导入时间',
  `audit_status` varchar(50) NOT NULL DEFAULT '未审核' COMMENT '审核状态：未审核、已审核待整改、已完成',
  `record_count` int(11) NOT NULL DEFAULT '0' COMMENT '导入记录数量',
  `audit_comment` text DEFAULT NULL COMMENT '审核意见',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_single_soldier` int(11) NOT NULL DEFAULT '0' COMMENT '是否单兵设备：0=否，1=是',
  `archive_type` varchar(50) DEFAULT NULL COMMENT '档案类型：新增、取推、补档案',
  PRIMARY KEY (`id`),
  KEY `file_name` (`file_name`),
  KEY `organization` (`organization`),
  KEY `audit_status` (`audit_status`),
  KEY `archive_type` (`archive_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备审核任务表';

-- 8. 设备审核明细表（audit_details）
CREATE TABLE IF NOT EXISTS `audit_details` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `task_id` int(11) NOT NULL COMMENT '审核任务ID',
  `device_code` varchar(100) NOT NULL COMMENT '设备编码',
  `original_device_code` varchar(100) DEFAULT NULL COMMENT '原设备编码',
  `device_name` varchar(200) NOT NULL COMMENT '设备名称',
  `division_code` varchar(50) NOT NULL COMMENT '行政区划编码',
  `monitor_point_type` varchar(10) NOT NULL COMMENT '监控点位类型：1=一类点，2=二类点，3=三类点，4=四类点',
  `pickup` varchar(50) DEFAULT NULL COMMENT '拾音器',
  `parent_device` varchar(100) DEFAULT NULL COMMENT '父设备',
  `construction_unit` varchar(200) NOT NULL COMMENT '建设单位/设备归属',
  `construction_unit_code` varchar(100) NOT NULL COMMENT '建设单位/平台归属代码',
  `management_unit` varchar(200) NOT NULL COMMENT '管理单位',
  `camera_dept` varchar(100) NOT NULL COMMENT '摄像机所属部门（警种）',
  `admin_name` varchar(50) NOT NULL COMMENT '管理员姓名',
  `admin_contact` varchar(50) NOT NULL COMMENT '管理员联系电话',
  `contractor` varchar(200) NOT NULL COMMENT '承建单位',
  `maintain_unit` varchar(200) NOT NULL COMMENT '维护单位',
  `device_vendor` varchar(100) NOT NULL COMMENT '设备厂商',
  `device_model` varchar(100) DEFAULT NULL COMMENT '设备型号',
  `camera_type` varchar(50) NOT NULL COMMENT '摄像机类型',
  `access_method` varchar(50) DEFAULT NULL COMMENT '接入方式',
  `camera_function_type` varchar(50) NOT NULL COMMENT '摄像机功能类型：1=车辆，2=人脸，空或其他=视频',
  `video_encoding_format` varchar(50) NOT NULL COMMENT '视频编码格式',
  `image_resolution` varchar(50) NOT NULL COMMENT '图像分辨率',
  `camera_light_property` varchar(50) DEFAULT NULL COMMENT '摄像机补光属性',
  `backend_structure` varchar(50) DEFAULT NULL COMMENT '后端结构化',
  `lens_type` varchar(50) DEFAULT NULL COMMENT '镜头类型',
  `installation_type` varchar(50) DEFAULT NULL COMMENT '安装类型',
  `height_type` varchar(50) NOT NULL COMMENT '高度类型',
  `jurisdiction_police` varchar(200) NOT NULL COMMENT '所属辖区公安机关',
  `installation_address` varchar(500) NOT NULL COMMENT '安装地址',
  `surrounding_landmark` varchar(500) NOT NULL COMMENT '周边标志',
  `longitude` decimal(10,7) NOT NULL COMMENT '经度',
  `latitude` decimal(10,7) NOT NULL COMMENT '纬度',
  `installation_location` varchar(50) NOT NULL COMMENT '摄像机安装位置室内外',
  `monitoring_direction` varchar(50) NOT NULL COMMENT '摄像机监控方位',
  `pole_number` varchar(50) NOT NULL COMMENT '立杆编号',
  `scene_picture` varchar(500) DEFAULT NULL COMMENT '摄像机实景图片',
  `networking_property` varchar(50) DEFAULT NULL COMMENT '联网属性',
  `access_network` varchar(50) NOT NULL COMMENT '接入网络',
  `ipv4_address` varchar(50) NOT NULL COMMENT 'IPv4地址',
  `ipv6_address` varchar(50) DEFAULT NULL COMMENT 'IPv6地址',
  `mac_address` varchar(50) NOT NULL COMMENT '设备MAC地址',
  `access_port` varchar(50) DEFAULT NULL COMMENT '访问端口',
  `associated_encoder` varchar(100) DEFAULT NULL COMMENT '关联编码器',
  `device_username` varchar(50) DEFAULT NULL COMMENT '设备用户名',
  `device_password` varchar(100) DEFAULT NULL COMMENT '设备口令',
  `channel_number` varchar(50) DEFAULT NULL COMMENT '通道号',
  `connection_protocol` varchar(50) DEFAULT NULL COMMENT '连接协议',
  `enabled_time` varchar(50) NOT NULL COMMENT '启用时间',
  `scrapped_time` varchar(50) DEFAULT NULL COMMENT '报废时间',
  `device_status` varchar(50) NOT NULL COMMENT '设备状态',
  `inspection_status` varchar(50) DEFAULT NULL COMMENT '巡检状态',
  `video_loss` int(11) DEFAULT NULL COMMENT '视频丢失',
  `color_distortion` int(11) DEFAULT NULL COMMENT '色彩失真',
  `video_blur` int(11) DEFAULT NULL COMMENT '视频模糊',
  `brightness_exception` int(11) DEFAULT NULL COMMENT '亮度异常',
  `video_interference` int(11) DEFAULT NULL COMMENT '视频干扰',
  `video_lag` int(11) DEFAULT NULL COMMENT '视频卡顿',
  `video_occlusion` int(11) DEFAULT NULL COMMENT '视频遮挡',
  `scene_change` int(11) DEFAULT NULL COMMENT '场景变更',
  `online_duration` bigint(20) DEFAULT NULL COMMENT '在线时长',
  `offline_duration` bigint(20) DEFAULT NULL COMMENT '离线时长',
  `signaling_delay` bigint(20) DEFAULT NULL COMMENT '信令时延',
  `video_stream_delay` bigint(20) DEFAULT NULL COMMENT '视频流时延',
  `key_frame_delay` bigint(20) DEFAULT NULL COMMENT '关键帧时延',
  `recording_retention_days` int(11) NOT NULL COMMENT '录像保存天数',
  `storage_device_code` varchar(100) DEFAULT NULL COMMENT '存储设备编码',
  `storage_channel_number` varchar(50) DEFAULT NULL COMMENT '存储通道号',
  `storage_type` varchar(50) DEFAULT NULL COMMENT '存储类型',
  `cache_settings` varchar(200) DEFAULT NULL COMMENT '缓存设置',
  `notes` text DEFAULT NULL COMMENT '备注',
  `collection_area_type` varchar(50) NOT NULL COMMENT '采集区域类型',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `audit_status` int(11) NOT NULL DEFAULT '0' COMMENT '建档状态：0=未审核未建档，1=已审核未建档，2=已建档',
  PRIMARY KEY (`id`),
  KEY `task_id` (`task_id`),
  KEY `device_code` (`device_code`),
  KEY `device_name` (`device_name`),
  KEY `management_unit` (`management_unit`),
  KEY `monitor_point_type` (`monitor_point_type`),
  KEY `update_time` (`update_time`),
  KEY `audit_status` (`audit_status`),
  CONSTRAINT `audit_details_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `audit_tasks` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备审核明细表';

-- 9. 卡口审核任务表（checkpoint_tasks）
CREATE TABLE IF NOT EXISTS `checkpoint_tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `file_name` varchar(200) NOT NULL COMMENT '档案名称',
  `organization` varchar(200) NOT NULL COMMENT '机构名称',
  `import_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '导入时间',
  `audit_status` varchar(50) NOT NULL DEFAULT '未审核' COMMENT '审核状态：未审核、已审核待整改、已完成',
  `record_count` int(11) NOT NULL DEFAULT '0' COMMENT '导入记录数量',
  `audit_comment` text DEFAULT NULL COMMENT '审核意见',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `archive_type` varchar(50) DEFAULT NULL COMMENT '档案类型：新增、取推、补档案',
  PRIMARY KEY (`id`),
  KEY `file_name` (`file_name`),
  KEY `organization` (`organization`),
  KEY `audit_status` (`audit_status`),
  KEY `archive_type` (`archive_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='卡口审核任务表';

-- ============================================
-- 初始化完成
-- ============================================
-- 
-- 注意：
-- 1. 如果checkpoint_details表已存在但没有task_id字段，需要手动执行以下ALTER语句：
--    ALTER TABLE `checkpoint_details` ADD COLUMN `task_id` int(11) DEFAULT NULL COMMENT '审核任务ID' AFTER `id`;
--    ALTER TABLE `checkpoint_details` ADD KEY `task_id` (`task_id`);
--    ALTER TABLE `checkpoint_details` ADD CONSTRAINT `checkpoint_details_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `checkpoint_tasks` (`id`) ON DELETE CASCADE;
--
-- 2. 执行完此SQL文件后，请执行 init-admin-user.sql 创建初始管理员账户
--

