-- 卡口审核任务表
CREATE TABLE IF NOT EXISTS `checkpoint_tasks` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `file_name` varchar(255) NOT NULL COMMENT '档案名称',
  `organization` varchar(100) NOT NULL COMMENT '机构/子公司名称',
  `import_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '导入时间',
  `audit_status` varchar(20) NOT NULL DEFAULT '未审核' COMMENT '审核状态：未审核、已审核待整改、已完成',
  `audit_comment` text DEFAULT NULL COMMENT '审核意见',
  `auditor` varchar(50) DEFAULT NULL COMMENT '审核人',
  `audit_time` timestamp NULL DEFAULT NULL COMMENT '审核时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_audit_status` (`audit_status`),
  KEY `idx_organization` (`organization`),
  KEY `idx_import_time` (`import_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='卡口审核任务表';

-- 卡口审核明细表（存储导入的Excel数据）
CREATE TABLE IF NOT EXISTS `checkpoint_details` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `task_id` bigint(20) unsigned NOT NULL COMMENT '审核任务ID，关联checkpoint_tasks表',
  `checkpoint_code` varchar(18) DEFAULT NULL COMMENT '卡口编号（*）',
  `original_checkpoint_code` varchar(18) DEFAULT NULL COMMENT '原卡口编号',
  `checkpoint_name` varchar(255) DEFAULT NULL COMMENT '卡口名称（*）',
  `checkpoint_address` varchar(255) DEFAULT NULL COMMENT '卡口地址（*）',
  `road_name` varchar(255) DEFAULT NULL COMMENT '道路名称（*）',
  `direction_type` varchar(50) DEFAULT NULL COMMENT '方向类型',
  `direction_description` varchar(2) DEFAULT NULL COMMENT '方向描述（*）',
  `direction_notes` varchar(255) DEFAULT NULL COMMENT '方向备注',
  `division_code` varchar(8) DEFAULT NULL COMMENT '行政区划（*）',
  `road_section_type` varchar(2) DEFAULT NULL COMMENT '路段类型（*）',
  `road_code` varchar(8) DEFAULT NULL COMMENT '道路代码（*）',
  `kilometer_or_intersection_number` varchar(6) DEFAULT NULL COMMENT '公里数/路口号（*）',
  `road_meter` varchar(6) DEFAULT NULL COMMENT '道路米数（*）',
  `pole_number` varchar(30) DEFAULT NULL COMMENT '立杆编号',
  `checkpoint_point_type` varchar(2) DEFAULT NULL COMMENT '卡口点位类型（*）',
  `checkpoint_location_type` varchar(2) DEFAULT NULL COMMENT '卡口位置类型（*）',
  `checkpoint_application_type` varchar(2) DEFAULT NULL COMMENT '卡口应用类型（*）',
  `has_interception_condition` varchar(2) DEFAULT NULL COMMENT '具备拦截条件（*）',
  `has_speed_measurement` varchar(2) DEFAULT NULL COMMENT '具备车辆测速功能',
  `has_realtime_video` varchar(2) DEFAULT NULL COMMENT '具备实时视频功能',
  `has_face_capture` varchar(2) DEFAULT NULL COMMENT '具备人脸抓拍功能',
  `has_violation_capture` varchar(2) DEFAULT NULL COMMENT '具备违章抓拍功能',
  `has_frontend_secondary_recognition` varchar(2) DEFAULT NULL COMMENT '具备前端二次识别功能',
  `is_boundary_checkpoint` varchar(2) DEFAULT NULL COMMENT '是否边界卡口（*）',
  `adjacent_area` varchar(20) DEFAULT NULL COMMENT '邻界地域（*）',
  `checkpoint_longitude` varchar(15) DEFAULT NULL COMMENT '卡口经度（*）',
  `checkpoint_latitude` varchar(15) DEFAULT NULL COMMENT '卡口纬度（*）',
  `checkpoint_scene_photo_url` varchar(30) DEFAULT NULL COMMENT '卡口实景照片地址',
  `checkpoint_status` varchar(2) DEFAULT NULL COMMENT '卡口状态（*）',
  `capture_trigger_type` varchar(2) DEFAULT NULL COMMENT '抓拍触发类型',
  `capture_direction_type` varchar(2) DEFAULT NULL COMMENT '抓拍方向类型（*）',
  `total_lanes` varchar(2) DEFAULT NULL COMMENT '车道总数（*）',
  `panoramic_camera_device_code` varchar(20) DEFAULT NULL COMMENT '全景球机设备编码（*）',
  `next_checkpoint_along_road` varchar(18) DEFAULT NULL COMMENT '沿线下一卡口编号',
  `next_checkpoint_opposite` varchar(18) DEFAULT NULL COMMENT '对向下一卡口编号',
  `next_checkpoint_left_turn` varchar(18) DEFAULT NULL COMMENT '左转下一卡口编号',
  `next_checkpoint_right_turn` varchar(18) DEFAULT NULL COMMENT '右转下一卡口编号',
  `next_checkpoint_u_turn` varchar(18) DEFAULT NULL COMMENT '掉头下一卡口编号',
  `construction_unit` varchar(30) DEFAULT NULL COMMENT '建设单位（*）',
  `management_unit` varchar(30) DEFAULT NULL COMMENT '管理单位（*）',
  `checkpoint_department` varchar(2) DEFAULT NULL COMMENT '卡口所属部门（*）',
  `admin_name` varchar(8) DEFAULT NULL COMMENT '管理员姓名（*）',
  `admin_contact` varchar(15) DEFAULT NULL COMMENT '管理员联系电话',
  `checkpoint_contractor` varchar(30) DEFAULT NULL COMMENT '卡口承建单位',
  `checkpoint_maintain_unit` varchar(30) DEFAULT NULL COMMENT '卡口维护单位',
  `alarm_receiving_department` varchar(15) DEFAULT NULL COMMENT '接警部门（*）',
  `alarm_receiving_department_code` varchar(15) DEFAULT NULL COMMENT '接警部门代码（*）',
  `alarm_receiving_phone` varchar(15) DEFAULT NULL COMMENT '接警电话（*）',
  `interception_department` varchar(15) DEFAULT NULL COMMENT '拦截部门（*）',
  `interception_department_code` varchar(15) DEFAULT NULL COMMENT '拦截部门代码（*）',
  `interception_department_contact` varchar(15) DEFAULT NULL COMMENT '拦截部门联系电话（*）',
  `terminal_code` varchar(20) DEFAULT NULL COMMENT '终端编码',
  `terminal_ip_address` varchar(20) DEFAULT NULL COMMENT '终端IP地址（*）',
  `terminal_port` varchar(5) DEFAULT NULL COMMENT '终端端口',
  `terminal_username` varchar(10) DEFAULT NULL COMMENT '终端用户名',
  `terminal_password` varchar(20) DEFAULT NULL COMMENT '终端密码',
  `terminal_vendor` varchar(50) DEFAULT NULL COMMENT '终端厂商',
  `checkpoint_enabled_time` varchar(30) DEFAULT NULL COMMENT '卡口启用时间（*）',
  `checkpoint_revoked_time` varchar(30) DEFAULT NULL COMMENT '卡口撤销时间',
  `notes` varchar(20) DEFAULT NULL COMMENT '备注',
  `checkpoint_device_type` varchar(2) DEFAULT NULL COMMENT '卡口设备类型（*）',
  `total_capture_cameras` varchar(2) DEFAULT NULL COMMENT '抓拍摄像机总数（*）',
  `central_control_code` varchar(20) DEFAULT NULL COMMENT '中控机编码',
  `central_control_ip_address` varchar(50) DEFAULT NULL COMMENT '中控机IP地址',
  `central_control_port` varchar(5) DEFAULT NULL COMMENT '中控机端口',
  `central_control_username` varchar(20) DEFAULT NULL COMMENT '中控机用户名',
  `central_control_password` varchar(20) DEFAULT NULL COMMENT '中控机密码',
  `central_control_vendor` varchar(50) DEFAULT NULL COMMENT '中控机厂商',
  `checkpoint_scrapped_time` varchar(20) DEFAULT NULL COMMENT '卡口报废时间',
  `total_antennas` varchar(20) DEFAULT NULL COMMENT '天线总数',
  `terminal_mac_address` varchar(30) DEFAULT NULL COMMENT '终端MAC地址（*）',
  `collection_area_type` varchar(20) DEFAULT NULL COMMENT '采集区域类型',
  `integrated_command_platform_checkpoint_code` varchar(20) DEFAULT NULL COMMENT '集成指挥平台卡口编号（组）',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `audit_status` int(11) NOT NULL DEFAULT 0 COMMENT '建档状态：0-未审核未建档，1-已审核未建档，2-已建档',
  PRIMARY KEY (`id`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_checkpoint_code` (`checkpoint_code`),
  CONSTRAINT `fk_checkpoint_details_task` FOREIGN KEY (`task_id`) REFERENCES `checkpoint_tasks` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='卡口审核明细表';

-- 机构名称字典表
CREATE TABLE IF NOT EXISTS `organizations` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `name` varchar(100) NOT NULL COMMENT '机构名称',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_name` (`name`),
  KEY `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='机构名称字典表';
